namespace NightGuard.Models;

public sealed class AppConfig
{
    public string RestrictionStart { get; set; } = "23:00";
    public string RestrictionEnd { get; set; } = "08:00";
    public bool BlockAllAppsDuringRestriction { get; set; }
    public bool EnableHostsBlocking { get; set; }
    public List<string> AlwaysAllowedProcesses { get; set; } =
    [
        "explorer.exe",
        "cmd.exe",
        "powershell.exe",
        "WindowsTerminal.exe",
        "notepad.exe",
        "idea64.exe",
        "idea.exe",
        "jetbrains-toolbox.exe",
        "WINWORD.EXE",
        "EXCEL.EXE",
        "POWERPNT.EXE",
        "ONENOTE.EXE",
        "OUTLOOK.EXE",
        "WPS.exe",
        "wps.exe",
        "et.exe",
        "wpp.exe",
        "chrome.exe",
        "msedge.exe",
        "msedgewebview2.exe",
        "Code.exe",
        "Cursor.exe",
        "Codex.exe",
        "node_repl.exe",
        "extension-host.exe",
        "crashpad_handler.exe",
        "node.exe",
        "git.exe",
        "git-remote-https.exe",
        "rg.exe",
        "fd.exe",
        "Clash Verge.exe",
        "clash.exe",
        "clash-meta.exe",
        "clash-verge-service.exe",
        "FlClash.exe",
        "FlClashHelperService.exe",
        "Clash for Windows.exe",
        "Clash Core Service.exe",
        "DesktopMgr64.exe",
        "DesktopService64.exe",
        "DesktopAITaskCenter.exe",
        "DesktopMgr.exe",
        "DesktopService.exe",
        "QQDesktopMgr.exe",
        "TencentDesktopMgr.exe",
        "PixPin.exe",
        "PixPinCapture.exe",
        "PixPinService.exe",
        "aw-qt.exe",
        "aw-server.exe",
        "aw-watcher-afk.exe",
        "aw-watcher-window.exe",
        "NVDisplay.Container.exe",
        "nvcontainer.exe",
        "nvsphelper64.exe",
        "NVIDIA Overlay.exe",
        "NVIDIA Share.exe",
        "NVIDIA Web Helper.exe",
        "NVIDIA App.exe",
        "Weixin.exe",
        "WeChat.exe",
        "WeChatAppEx.exe",
        "WeChatBrowser.exe",
        "WeChatUtility.exe",
        "WeChatPlayer.exe",
        "YoudaoDict.exe",
        "YoudaoDictHelper.exe",
        "YoudaoEDIT.exe",
        "YoudaoWSH.exe",
        "YoudaoOcr.exe",
        "YoudaoDesktopDict.exe",
        "Another Redis Desktop Manager.exe",
        "Apifox.exe",
        "Docker Desktop.exe",
        "docker.exe",
        "docker-sandbox.exe",
        "com.docker.backend.exe",
        "com.docker.build.exe",
        "com.docker.service.exe",
        "com.docker.proxy.exe",
        "com.docker.cli.exe",
        "eclipse.exe",
        "eNSP.exe",
        "DBeaver.exe",
        "HBuilderX.exe",
        "GoLand64.exe",
        "GoLand.exe",
        "Navicat.exe",
        "MobaXterm.exe",
        "VirtualBox.exe",
        "VirtualBoxVM.exe",
        "vmware.exe",
        "vmware-vmx.exe",
        "pycharm64.exe",
        "pycharm.exe",
        "SQLyog.exe",
        "WeChatDevTools.exe",
        "wampmanager.exe",
        "wampserver64.exe",
        "httpd.exe",
        "mysqld.exe",
        "php.exe"
    ];
    public List<string> BlockedProcesses { get; set; } = ["steam.exe", "game.exe"];
    public List<string> BlockedDomains { get; set; } =
    [
        "douyin.com",
        "www.douyin.com",
        "live.douyin.com",
        "creator.douyin.com",
        "v.douyin.com",
        "iesdouyin.com",
        "www.iesdouyin.com",
        "amemv.com",
        "www.amemv.com",
        "douyincdn.com",
        "www.douyincdn.com",
        "douyinpic.com",
        "www.douyinpic.com",
        "douyinvod.com",
        "www.douyinvod.com",
        "bilibili.com",
        "www.bilibili.com",
        "m.bilibili.com",
        "space.bilibili.com",
        "live.bilibili.com",
        "api.bilibili.com",
        "api.bilibili.tv",
        "biliapi.net",
        "biliapi.com",
        "bilivideo.com",
        "bilibili.tv",
        "hdslb.com",
        "upos-hz-mirrorakam.akamaized.net"
    ];
    public List<string> AlwaysAllowedDomains { get; set; } =
    [
        "chatgpt.com",
        "chat.openai.com",
        "claude.ai",
        "gemini.google.com",
        "perplexity.ai"
    ];
    public int UnlockDelayMinutes { get; set; } = 5;
    public int TemporaryAllowanceMinutes { get; set; } = 10;
    public int MaxUnlocksPerNight { get; set; } = 2;
    public string SettingsPasswordHash { get; set; } = "";
    public bool StartWithWindows { get; set; }
    public List<string> NightFocusProcesses { get; set; } =
    [
        "Codex.exe",
        "Cursor.exe"
    ];
    public List<string> NightFocusDomains { get; set; } = [];
}
